Imports System.IO
Public Class FormReport
    Private Sub frmReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        LoadReport()
    End Sub

    Private Sub LoadReport()
        Dim todayReport As String = Path.Combine(Application.StartupPath, $"DailyReport_{DateTime.Now:yyyyMMdd}.txt")

        If File.Exists(todayReport) Then
            txtReport.Text = File.ReadAllText(todayReport)
        Else
            txtReport.Text = "No report found for today. Click 'Generate' to create one."
        End If
    End Sub

    Private Sub btnGenerate_Click(sender As Object, e As EventArgs) Handles btnGenerate.Click
        Dim reportPath As String = Path.Combine(Application.StartupPath, $"DailyReport_{DateTime.Now:yyyyMMdd}.txt")

        If Not File.Exists("transactions.txt") Then
            MessageBox.Show("No transactions found.", "Report", MessageBoxButtons.OK, MessageBoxIcon.Information)
            Exit Sub
        End If

        Dim totalSales As Decimal = 0
        Dim totalTransactions As Integer = 0
        Dim lines() As String = File.ReadAllLines("transactions.txt")

        For Each line As String In lines
            If line.StartsWith("Total: RM ") Then
                Dim amountStr As String = line.Replace("Total: RM ", "").Trim()
                Dim amount As Decimal
                If Decimal.TryParse(amountStr, amount) Then
                    totalSales += amount
                    totalTransactions += 1 '++
                End If
            End If
        Next

        Dim report As String = "===== DAILY SALES REPORT =====" & vbCrLf &
                               "Date: " & DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") & vbCrLf &
                               "--------------------------------" & vbCrLf &
                               "Total Transactions: " & totalTransactions & vbCrLf &
                               "Total Sales: RM " & totalSales.ToString("0.00") & vbCrLf &
                               "--------------------------------" & vbCrLf &
                               "Generated by System"

        File.WriteAllText(reportPath, report)
        MessageBox.Show("Daily report generated successfully!", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information)

        Process.Start("C:\Windows\System32\notepad.exe", reportPath)

        LoadReport()
    End Sub

    Private Sub btnBack_Click(sender As Object, e As EventArgs) Handles btnBack.Click
        MainUI.Show()
        Me.Hide()
    End Sub
End Class